# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
- develop

pool:
  vmImage: ubuntu-latest

steps:

- task: JavaToolInstaller@0
  name: java17InstallTask
  inputs:
    versionSpec: '17'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

# checking the java version
#- script: | 
#          mvn -version
#          echo $JAVA_HOME
#          java -version
#  name: versionCheck

# mvn package command
#- task: Maven@4
#  name: mvntask
#  inputs:
#    mavenPomFile: 'code/pom.xml'
#    options: '-e'
#    publishJUnitResults: false
#    javaHomeOption: 'JDKVersion'
#    mavenVersionOption: 'Default'
#    mavenOptions: '-Xmx512m'
#    mavenAuthenticateFeed: false
#    effectivePomSkip: false
#    sonarQubeRunAnalysis: false

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'bogaSonarCloud'
    organization: 'boga'
    scannerMode: 'Other'
    extraProperties: |
      #sonar.exclusions=**/*.bin
      sonar.projectVersion=1.0.0.0
      sonar.projectName=javaPetClinicApp
      #sonar.sources=src/java/main
      sonar.language=java
      sonar.sourceEncoding=UTF-8
- task: Maven@4
  inputs:
    mavenPomFile: 'code/pom.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    codeCoverageToolOption: 'JaCoCo'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: true
    isJacocoCoverageReportXML: true
    sqMavenPluginVersionChoice: 'latest'

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '120'