# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main
- develop

pool:
  vmImage: ubuntu-latest

steps:

- script: | 
          mvn -version
          echo $JAVA_HOME
- task: Maven@4
  inputs:
    mavenPomFile: 'code/pom.xml'
    options: '-e'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenOptions: '-Xmx512m'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    
#- task: Maven@4
#  inputs:
#    mavenPomFile: 'code/pom.xml'
#    publishJUnitResults: false
#    javaHomeOption: 'JDKVersion'
#    mavenVersionOption: 'Default'
#    mavenAuthenticateFeed: false
#    effectivePomSkip: false
#    sonarQubeRunAnalysis: false

#Code by Maven template in Azure Pipelines
#- task: Maven@3
#  inputs:
#    mavenPomFile: 'code/pom.xml'
#    mavenOptions: '-Xmx3072m'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.8'
#    jdkArchitectureOption: 'x64'
#    publishJUnitResults: true
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    goals: 'package'